#!/usr/bin/python3

import sys

def factorize_number(n):
    # Function to factorize a number into a product of two smaller numbers
    factors = []
    for i in range(2, n // 2 + 1):
        if n % i == 0:
            factors.append((i, n // i))
    return factors

def factorize_numbers_from_file(file_path):
    # Function to read numbers from a file and factorize them
    with open(file_path, 'r') as file:
        for line in file:
            n = int(line.strip())
            factorizations = factorize_number(n)
            for factorization in factorizations:
                print("{}={}*{}".format(n, factorization[0], factorization[1]))

if __name__ == '__main__':
    # Main entry point of the program
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    
    file_path = sys.argv[1]
    factorize_numbers_from_file(file_path)

